name: ChatGPT Bot

on:
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened

env:
  CHATGPT_API_KEY: ${{ secrets.OPENAI_KEY }}

jobs:
  answer-question:
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.title, 'Q:') }}
    name: Answer Question
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Conversations
        uses: actions/cache@v3
        with:
          path: ~/.chatgpt
          key: conversations-${{ github.event.issue.number }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: conversations-${{ github.event.issue.number }}-
      - uses: kezhenxu94/chatgpt-java/chatgpt-cli@v0.9.0
      - name: Question
        if: github.event_name == 'issues'
        env:
          QUESTION: ${{ github.event.issue.title }}
        run: echo "QUESTION=${QUESTION#'Q:'}" >> $GITHUB_ENV
      - name: Question
        if: github.event_name == 'issue_comment'
        env:
          QUESTION: ${{ github.event.comment.body }}
        run: echo "QUESTION=${QUESTION#"Q:"}" >> $GITHUB_ENV
      - name: Answer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
        run: |
          envsubst < .github/workflows/chatgpt-script.sh > chatgpt-script.sh
          chatgpt -Dspring.banner.location=file://$(pwd)/.github/workflows/banner.txt @chatgpt-script.sh | tee -a answer.txt
          
          gh issue comment $ISSUE -F answer.txt


